environment          = "production"
aws_region           = "us-east-1"
vpc_cidr             = "10.2.0.0/16"
public_subnet_cidr   = "10.2.1.0/24"
availability_zone    = "us-east-1a"
instance_type        = "t3.medium"
